# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-25 15:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text="Nom del model de l'arma", max_length=30, unique=True, verbose_name='Nom')),
                ('imatge', models.ImageField(help_text="Imatge de l'arma", upload_to='Arma', verbose_name='Imatge')),
                ('silueta', models.ImageField(help_text="Silueta de l'arma", upload_to='Arma', verbose_name='Silueta')),
                ('descripcio', models.TextField(help_text="Petita descripcio de l'arma", max_length=1300, verbose_name='Descripci\xf3')),
                ('dany', models.IntegerField(help_text='Dany que fa cada impacte', verbose_name='Dany')),
                ('velocitat', models.IntegerField(help_text='Velocitat a la que va el projectil', verbose_name='Velocitat')),
                ('calormax', models.IntegerField(help_text="Limit de calor que te l'arma fins que deixa de disparar", verbose_name='CalorMaxim')),
                ('calorgen', models.IntegerField(help_text="Calor que genera l'arma per cada tir", verbose_name='CalorGenerat')),
                ('preucredits', models.IntegerField(help_text='El preu de la nau en credits del joc', verbose_name='PreuCredits')),
            ],
        ),
        migrations.CreateModel(
            name='Fabricant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='El nom del fabricant del producte.', max_length=20, unique=True, verbose_name='Nom')),
                ('logo', models.ImageField(help_text='Logo del fabricant', upload_to='Logo', verbose_name='Logo')),
                ('especialitzacio', models.TextField(help_text='Descripcio del fabricant i quina es la especialitzacio de la empresa', max_length=800, verbose_name='Especialitzaci\xf3')),
            ],
        ),
        migrations.CreateModel(
            name='Misil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Nom del model del misil', max_length=30, unique=True, verbose_name='Nom')),
                ('imatge', models.ImageField(help_text='Imatge del misil', upload_to='Misil', verbose_name='Imatge')),
                ('silueta', models.ImageField(help_text='Silueta del misil', upload_to='Misil', verbose_name='Silueta')),
                ('descripcio', models.TextField(help_text='Petita descripcio del misil', max_length=800, verbose_name='Descripci\xf3')),
                ('dany', models.IntegerField(help_text='Dany que fa cada imapacte', verbose_name='Dany')),
                ('velocitat', models.IntegerField(help_text='Velocitat a la que va el misil', verbose_name='Velocitat')),
                ('salut', models.IntegerField(help_text='Vida que te el misil avans de explotar', verbose_name='salut')),
                ('guiat', models.BooleanField(default=False, help_text='El misil segueix a el enemic o no', verbose_name='Guiat')),
                ('preucredits', models.IntegerField(help_text='El preu de la nau en credits del joc', verbose_name='PreuCredits')),
            ],
        ),
        migrations.CreateModel(
            name='Nau',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Nom del model de la nau', max_length=30, unique=True, verbose_name='Nom')),
                ('imatge', models.ImageField(help_text='Imatge de la nau', upload_to='Nau', verbose_name='Imatge')),
                ('silueta', models.ImageField(help_text='Silueta de la nau', upload_to='Nau', verbose_name='Silueta')),
                ('descripcio', models.TextField(help_text='Petita descripcio de la nau', max_length=800, verbose_name='Descripci\xf3')),
                ('video', models.CharField(blank=True, help_text="La demostraci\xf3 mitjan\xe7ant una URL d'un v\xeddeo.", max_length=150, null=True, verbose_name='Demostraci\xf3')),
                ('salut', models.IntegerField(help_text='Punts de salut que te la nau', verbose_name='salut')),
                ('escuts', models.IntegerField(help_text='Punts de escut que te la nau', verbose_name='Escuts')),
                ('velocitat', models.IntegerField(help_text='Velocitat a la que es despla\xe7a la nau', verbose_name='Velocitat')),
                ('disipaciocal', models.IntegerField(help_text='Quantitat de calor que disipa', verbose_name='Disipaci\xf3Calor')),
                ('numarmes', models.IntegerField(help_text='Quantitat de armes que porta la nau', verbose_name='NumeroArmes')),
                ('nummisils', models.IntegerField(help_text='Quantitat de misils que porta la nau', verbose_name='NumeroMisils')),
                ('preucredits', models.IntegerField(help_text='El preu de la nau en credits del joc', verbose_name='PreuCredits')),
                ('preu', models.DecimalField(decimal_places=2, help_text='El preu del producte en diners.', max_digits=5, verbose_name='Preu')),
                ('armes', models.ManyToManyField(help_text='Les armes que porta equipada la nau', to='naus.Arma', verbose_name='Armes')),
                ('fabricant', models.ForeignKey(help_text='Fabricant de la nau', on_delete=django.db.models.deletion.CASCADE, to='naus.Fabricant', verbose_name='Fabricant')),
                ('misil', models.ForeignKey(help_text='El tipus de misil que porta equipada la nau', on_delete=django.db.models.deletion.CASCADE, to='naus.Misil', verbose_name='Misil')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='nau',
            unique_together=set([('nom', 'fabricant')]),
        ),
    ]
